/*This script has been, partially or completely, generated by the Fungus.GenerateVariableWindow*/
using UnityEditor;
using UnityEngine;

namespace Fungus.EditorUtils
{
    [CustomPropertyDrawer(typeof(Collider2DData))]
    public class Collider2DDataDrawer : VariableDataDrawer<Collider2DVariable>
    { }
}