/*This script has been, partially or completely, generated by the Fungus.GenerateVariableWindow*/
using UnityEditor;
using UnityEngine;

namespace Fungus.EditorUtils
{
    [CustomPropertyDrawer(typeof(Rigidbody2DData))]
    public class Rigidbody2DDataDrawer : VariableDataDrawer<Rigidbody2DVariable>
    { }
}