/*This script has been, partially or completely, generated by the Fungus.GenerateVariableWindow*/
using UnityEditor;
using UnityEngine;

namespace Fungus.EditorUtils
{
    [CustomPropertyDrawer(typeof(Vector4Data))]
    public class Vector4DataDrawer : VariableDataDrawer<Vector4Variable>
    { }
}