/*This script has been, partially or completely, generated by the Fungus.GenerateVariableWindow*/
using UnityEditor;
using UnityEngine;

namespace Fungus.EditorUtils
{
    [CustomPropertyDrawer(typeof(Vector2Data))]
    public class Vector2DataDrawer : VariableDataDrawer<Vector2Variable>
    { }
}