/*This script has been, partially or completely, generated by the Fungus.GenerateVariableWindow*/
using UnityEditor;
using UnityEngine;

namespace Fungus.EditorUtils
{
    [CustomPropertyDrawer(typeof(Vector3Data))]
    public class Vector3DataDrawer : VariableDataDrawer<Vector3Variable>
    { }
}