/*This script has been, partially or completely, generated by the Fungus.GenerateVariableWindow*/
using UnityEngine;


namespace Fungus
{
    /// <summary>
    /// Collision variable type.
    /// </summary>
    [VariableInfo("Other", "Collision", IsPreviewedOnly = true)]
    [AddComponentMenu("")]
	[System.Serializable]
	public class CollisionVariable : VariableBase<UnityEngine.Collision>
	{ }
}