/*This script has been, partially or completely, generated by the Fungus.GenerateVariableWindow*/
using UnityEngine;


namespace Fungus
{
    /// <summary>
    /// ControllerColliderHit variable type.
    /// </summary>
    [VariableInfo("Other", "ControllerColliderHit", IsPreviewedOnly = true)]
    [AddComponentMenu("")]
	[System.Serializable]
	public class ControllerColliderHitVariable : VariableBase<UnityEngine.ControllerColliderHit>
	{ }
}